
package mymovies;

import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import model.Movie;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;
import model.FavoriteList;



/**
 *
 * @author Periklis Bouzanis
 */
public class MoviesSearchForm extends javax.swing.JFrame {

    /**
     * Creates new form moviesSearchGUI
     */
    public MoviesSearchForm(MainMenu parent) {
        this.parent = parent;
        initComponents();
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        bindingGroup = new org.jdesktop.beansbinding.BindingGroup();

        em = java.beans.Beans.isDesignTime() ? null : javax.persistence.Persistence.createEntityManagerFactory("myMoviesPU").createEntityManager();
        favoriteListQuery = java.beans.Beans.isDesignTime() ? null : em.createQuery("SELECT f.name FROM FavoriteList f");
        favoriteListList = java.beans.Beans.isDesignTime() ? java.util.Collections.emptyList() : favoriteListQuery.getResultList();
        movieTypeLabel = new javax.swing.JLabel();
        movieTypeComboBox = new javax.swing.JComboBox<>();
        movieSearchButton = new javax.swing.JButton();
        resetChoicesButton = new javax.swing.JButton();
        yearMovieLabel = new javax.swing.JLabel();
        yearMovieFieldEditor = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        movieResultTable = new javax.swing.JTable();
        favoriteListComboBox = new javax.swing.JComboBox<>();
        addToListLabel = new javax.swing.JLabel();
        removeFromListButton = new javax.swing.JButton();
        headerJPanel = new javax.swing.JPanel();
        headerJLaber = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setTitle("Αναζήτηση Ταινιών");

        org.jdesktop.beansbinding.Binding binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, this, org.jdesktop.beansbinding.ELProperty.create("${defaultCloseOperation}"), this, org.jdesktop.beansbinding.BeanProperty.create("defaultCloseOperation"));
        bindingGroup.addBinding(binding);

        movieTypeLabel.setFont(new java.awt.Font("Arial Black", 2, 12)); // NOI18N
        movieTypeLabel.setText("Επιλογή Είδους Ταινίας");

        movieTypeComboBox.setFont(new java.awt.Font("Arial Black", 2, 12)); // NOI18N
        movieTypeComboBox.setMaximumRowCount(4);
        movieTypeComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "<Κανένα>", "Action", "Romance", "Science Fiction" }));
        movieTypeComboBox.setToolTipText("Πρέπει να επιλέξετε είδος ταινίας και έτος κυκλοφορίας");
        movieTypeComboBox.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        movieTypeComboBox.setFocusCycleRoot(true);
        movieTypeComboBox.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                movieTypeComboBoxMouseClicked(evt);
            }
        });
        movieTypeComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                movieTypeComboBoxActionPerformed(evt);
            }
        });
        movieTypeComboBox.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                movieTypeComboBoxKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                movieTypeComboBoxKeyTyped(evt);
            }
        });

        movieSearchButton.setFont(new java.awt.Font("Arial Black", 2, 12)); // NOI18N
        movieSearchButton.setText("Αναζήτηση");
        movieSearchButton.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        movieSearchButton.setDoubleBuffered(true);
        movieSearchButton.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                movieSearchButtonFocusLost(evt);
            }
        });
        movieSearchButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                movieSearchButtonActionPerformed(evt);
            }
        });

        resetChoicesButton.setFont(new java.awt.Font("Arial Black", 2, 12)); // NOI18N
        resetChoicesButton.setText("Καθαρισμός Επιλογών");
        resetChoicesButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetChoicesButtonActionPerformed(evt);
            }
        });

        yearMovieLabel.setFont(new java.awt.Font("Arial Black", 2, 12)); // NOI18N
        yearMovieLabel.setText("Έτος Κυκολοφορίας");

        yearMovieFieldEditor.setColumns(4);
        yearMovieFieldEditor.setFont(new java.awt.Font("Arial Black", 2, 12)); // NOI18N
        yearMovieFieldEditor.setForeground(new java.awt.Color(153, 153, 153));
        yearMovieFieldEditor.setToolTipText("Πρέπει να συμπληρώσετε έτος κυκλοφορίας της ταινίας");
        yearMovieFieldEditor.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        yearMovieFieldEditor.setHighlighter(null);
        yearMovieFieldEditor.setInheritsPopupMenu(true);
        yearMovieFieldEditor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                yearMovieFieldEditorActionPerformed(evt);
            }
        });
        yearMovieFieldEditor.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                yearMovieFieldEditorKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                yearMovieFieldEditorKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                yearMovieFieldEditorKeyTyped(evt);
            }
        });

        movieResultTable.setAutoCreateRowSorter(true);
        movieResultTable.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        movieResultTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Τίτλος Ταινίας", "Βαθμολογία", "Περιγραφή"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Double.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        //Επιλογή στήλης Βαθμολογία για ταξινόμηση
        DefaultTableModel model =  (DefaultTableModel) movieResultTable.getModel();
        TableRowSorter<DefaultTableModel> sorter = new TableRowSorter<DefaultTableModel>(model);
        sorter.setSortable(0, false);
        sorter.setSortable(2, false);
        movieResultTable.setRowSorter(sorter);
        movieResultTable.setToolTipText("Μπορείτε να ταξινομήσετε ανα Βαθμολογία");
        movieResultTable.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_ALL_COLUMNS);
        movieResultTable.setColumnSelectionAllowed(true);
        movieResultTable.setNextFocusableComponent(favoriteListComboBox);
        movieResultTable.getTableHeader().setReorderingAllowed(false);
        movieResultTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                movieResultTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(movieResultTable);
        movieResultTable.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);

        org.jdesktop.swingbinding.JComboBoxBinding jComboBoxBinding = org.jdesktop.swingbinding.SwingBindings.createJComboBoxBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, favoriteListList, favoriteListComboBox);
        bindingGroup.addBinding(jComboBoxBinding);

        favoriteListComboBox.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                favoriteListComboBoxItemStateChanged(evt);
            }
        });
        favoriteListComboBox.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                favoriteListComboBoxMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                favoriteListComboBoxMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                favoriteListComboBoxMouseReleased(evt);
            }
        });
        favoriteListComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                favoriteListComboBoxActionPerformed(evt);
            }
        });

        addToListLabel.setFont(new java.awt.Font("Arial", 3, 12)); // NOI18N
        addToListLabel.setText("Προσθήκη σε Λίστα");

        removeFromListButton.setFont(new java.awt.Font("Arial Black", 3, 12)); // NOI18N
        removeFromListButton.setText("Αφαίρεση από Λίστα");
        removeFromListButton.setToolTipText("Πατήστε για αφαίρεση από Λίστα");
        removeFromListButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeFromListButtonActionPerformed(evt);
            }
        });

        headerJPanel.setBackground(new java.awt.Color(204, 255, 255));
        headerJPanel.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        headerJLaber.setBackground(new java.awt.Color(44, 196, 158));
        headerJLaber.setDisplayedMnemonic('\u03c3');
        headerJLaber.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        headerJLaber.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        headerJLaber.setText("<html><strong>My Movies</strong></html>");
        headerJLaber.setToolTipText("Αρχικό Μενού");
        headerJLaber.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        javax.swing.GroupLayout headerJPanelLayout = new javax.swing.GroupLayout(headerJPanel);
        headerJPanel.setLayout(headerJPanelLayout);
        headerJPanelLayout.setHorizontalGroup(
            headerJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(headerJPanelLayout.createSequentialGroup()
                .addGap(318, 318, 318)
                .addComponent(headerJLaber, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        headerJPanelLayout.setVerticalGroup(
            headerJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, headerJPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(headerJLaber, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jLabel1.setFont(new java.awt.Font("Arial", 3, 24)); // NOI18N
        jLabel1.setText("Πίνακας Αποτελεσμάτων Αναζήτησης");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(196, 196, 196)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(movieTypeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(movieSearchButton))
                                .addGap(78, 78, 78)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(resetChoicesButton)
                                    .addComponent(yearMovieLabel)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(movieTypeComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(favoriteListComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(25, 25, 25)
                                        .addComponent(addToListLabel)))
                                .addGap(78, 78, 78)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(yearMovieFieldEditor, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(removeFromListButton))))
                        .addGap(0, 206, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(headerJPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 679, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(100, 100, 100))
            .addGroup(layout.createSequentialGroup()
                .addGap(235, 235, 235)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 448, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {movieSearchButton, movieTypeComboBox, resetChoicesButton, yearMovieFieldEditor});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(headerJPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 337, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(addToListLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(favoriteListComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(removeFromListButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 66, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(movieTypeLabel)
                    .addComponent(yearMovieLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(movieTypeComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(yearMovieFieldEditor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(movieSearchButton)
                    .addComponent(resetChoicesButton))
                .addGap(23, 23, 23))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {movieTypeLabel, yearMovieLabel});

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {movieSearchButton, resetChoicesButton});

        movieTypeComboBox.getAccessibleContext().setAccessibleDescription("Πρέπει να επιλέξετε είδος ταινίας");

        bindingGroup.bind();

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /*  
        Ανάκτηση ταινιών από Βάση Δέδομένων βάσει κριτιρίων αναζήτησης 
        κατοπίν πατήματος του Κουμπιού "Αναζήτηση"
    */
    private void movieSearchButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_movieSearchButtonActionPerformed
        // TODO add your handling code here: 
        
        //Ανάκτηση της επιλογής του τύπου της ταινίας
        String searchType = (String)movieTypeComboBox.getSelectedItem();
        ////Ανάκτηση του έτους κυκλοφορίας της ταινίας
        String searchYear = yearMovieFieldEditor.getText();
        
        //Ανάκτηση ταινιών από την Βάση Δεμομένων βάσει κριτιρίων αναζήτησης
        retrieveMovieList = retrieveFromDBMovieTable(searchType,searchYear);
        
        //Προσθήκη των αποτελεσμάτων αναζήτησης στον πίνακα movieResultTable               
        addRowtoJTable(retrieveMovieList);       
    }//GEN-LAST:event_movieSearchButtonActionPerformed
   
    private void movieTypeComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_movieTypeComboBoxActionPerformed
        // TODO add your handling code here:
       
    }//GEN-LAST:event_movieTypeComboBoxActionPerformed

    private void yearMovieFieldEditorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_yearMovieFieldEditorActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_yearMovieFieldEditorActionPerformed

    /*
        Καθαρισμός των επιλογών κριτιρών αναζήτησης πατώντας  
        το κουμπί "Καθαρισμός Επιλογών"
    */
    private void resetChoicesButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetChoicesButtonActionPerformed
        // TODO add your handling code here:
        //Σβήσιμο του πεδίου της κυκλοφορίας του έτους
        yearMovieFieldEditor.setText(null);
        //Αρχικοποίηση του πεδίου του είδους της ταινίας στην τιμή <Κανένα>
        movieTypeComboBox.setSelectedIndex(0);
        //Απενεργοποίηση του κουμπιού "Αναζήτηση"
        movieSearchButton.setEnabled(false); 
    }//GEN-LAST:event_resetChoicesButtonActionPerformed

    private void movieTypeComboBoxMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_movieTypeComboBoxMouseClicked
        // TODO add your handling code here:
        
        
    }//GEN-LAST:event_movieTypeComboBoxMouseClicked

    private void movieSearchButtonFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_movieSearchButtonFocusLost
        // TODO add your handling code here:
        
    }//GEN-LAST:event_movieSearchButtonFocusLost

    /*
        Ελεχος από το πεδίο είδους ταινίας για ύπαρξη τιμής  
        στα πεδία του είδους ταινίας και έτος κυκλοφορίας για  
        ενεργοποίηση/απενεργοποίηση του κουμπιού "Αναζήτηση"
    */
    private void movieTypeComboBoxKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_movieTypeComboBoxKeyReleased
        // TODO add your handling code here:
        /*
            Αν το πεδίο του τύπου ταινίας και το πεδίο του έτους κυκλοφορίας
            δεν είναι άδεια και τα δύο, το κουμπί "Αναζήτηση" ενεργοποιείται
            διαφορετικά απενεργοποιειται
        */
        if(!movieTypeComboBox.getSelectedItem().equals("<Κανένα>" ) 
                && !(yearMovieFieldEditor.getText().equals(null)))
            movieSearchButton.setEnabled(true);
        else
           movieSearchButton.setEnabled(false); 
        
    }//GEN-LAST:event_movieTypeComboBoxKeyReleased

    private void yearMovieFieldEditorKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_yearMovieFieldEditorKeyTyped
        // TODO add your handling code here:       
    }//GEN-LAST:event_yearMovieFieldEditorKeyTyped

    private void yearMovieFieldEditorKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_yearMovieFieldEditorKeyReleased
        // TODO add your handling code here:        
    }//GEN-LAST:event_yearMovieFieldEditorKeyReleased

    private void movieTypeComboBoxKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_movieTypeComboBoxKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_movieTypeComboBoxKeyTyped

    private void favoriteListComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_favoriteListComboBoxActionPerformed
        // TODO add your handling code here:            
    }//GEN-LAST:event_favoriteListComboBoxActionPerformed

    /*
        Χειρισμός των αποτελεσμάτων του πίνακα αναζήτησης ταινιών με 
        επιλογή μιας εγγραφής ταινίας
    */
    private void movieResultTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_movieResultTableMouseClicked
        // TODO add your handling code here:
        //Ανάκτηση της επιλεγμένης ταινίας από το μοντέλο του πίνακα 
        Movie movieSelected = retrieveMovieList.get(movieResultTable.convertRowIndexToModel(movieResultTable.getSelectedRow()));
        
        /*
            Ελεγχος της ταινίας αν ανήκει ήδη σε Αγαπημένη λίστα. Αν ανήκει,
            προβάλλεται η λίστα που ανήκει ήδη
            
        */
        try {
            if(!movieSelected.getFavoriteListId().equals(null)){
                JOptionPane.showMessageDialog(rootPane,"Η ταινία ανήκει ήδη σε Αγαπημένη Λίστα."
                    + "\nΕπιλέξτε διαφορετική Αγαπημένη Λίστα για αλλαγή"
                    + "\n ή αφήστε την εμφανιζόμενη Αγαπημένη Λίστα","Μήνυμα",JOptionPane.INFORMATION_MESSAGE);
                 favoriteListComboBox.setSelectedItem(movieSelected.getFavoriteListId().getName());
            }    
        }catch (NullPointerException e){
            JOptionPane.showMessageDialog(rootPane, "Η ταινία δεν ανήκει σε Αγαπημένη Λίστα."
                    + "\nΕπιλέξτε Αγαπημένη Λίστα για προσθήκη","Μήνυμα",JOptionPane.INFORMATION_MESSAGE);
        }   
    }//GEN-LAST:event_movieResultTableMouseClicked

    /*
        Επιλογή της Αγαπημένης Λίστας και προσθήκη της επιλεγμένης
        ταινίας σε αυτή
    */
    private void favoriteListComboBoxMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_favoriteListComboBoxMouseClicked
        // TODO add your handling code here:
        //Ανάκτηση της ταινίας από το μοντέλο του πίνακα αναζήτησης                     
        Movie movieSelected = retrieveMovieList.get(movieResultTable.convertRowIndexToModel(movieResultTable.getSelectedRow()));
        movieSelected.setFavoriteListId(retrieveFavoriteListFromDB(favoriteListComboBox.getSelectedIndex()));
        /*
            Ενημέρωση της Βάσης δεδομένων με την αλλαγή στην αγαπημένη λίστα
            της επιλεγμένης ταινίας
        */
        updateMovieTabLe (movieSelected);
        
        JOptionPane.showMessageDialog(rootPane, ("Η ταινία προστέθηκε στην Αγαπημένη Λίστα"
                    + "\n\"" + movieSelected.getFavoriteListId().getName()+"\"" ),"Μήνυμα",JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_favoriteListComboBoxMouseClicked

    private void favoriteListComboBoxItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_favoriteListComboBoxItemStateChanged
        // TODO add your handling code here:
        
    }//GEN-LAST:event_favoriteListComboBoxItemStateChanged

    private void favoriteListComboBoxMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_favoriteListComboBoxMousePressed
        // TODO add your handling code here:        
    }//GEN-LAST:event_favoriteListComboBoxMousePressed

    private void favoriteListComboBoxMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_favoriteListComboBoxMouseReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_favoriteListComboBoxMouseReleased

    /*
        Αφαίρεση της επιλεγμένης ταινίας από την Αγαπημένη λίστα με το 
        πάτημα του κουμπιού "Διαγραφή από Αγαπημένη Λίστα".Αν η ταινία
        δεν ανήκει σε λίστα,εμφανίζεται αντίστοιχο μήνυμα 
    */
    private void removeFromListButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeFromListButtonActionPerformed
        // TODO add your handling code here:
        
        Movie movieSelected = retrieveMovieList.get(movieResultTable.convertRowIndexToModel(movieResultTable.getSelectedRow()));
        try {
            //Ελεγχος αν η ταινία ανήκει σε Αγαπημένη λίστα
            movieSelected.getFavoriteListId().equals(null); 
            // Αν ανήκει αφαίρεσή της από την λίστα
            movieSelected.setFavoriteListId(null);
            //Η επιλογή των Αγαπημένων Λιστών αρχικοποιείται
            favoriteListComboBox.setSelectedIndex(0);
            
            /*
            Ενημέρωση της Βάσης δεδομένων με την αλλαγή στην αγαπημένη λίστα
            της επιλεγμένης ταινίας
            */
            updateMovieTabLe (movieSelected);
            
            JOptionPane.showMessageDialog(rootPane, "Η ταινία διαγράφηκε από την"
                + "\nΑγαπημένη Λίστα","Μήνυμα",JOptionPane.INFORMATION_MESSAGE);          
        }catch (NullPointerException e){
            //Μήνυμα εφόσον η ταινία δεν ανήκει σε λίστα
            JOptionPane.showMessageDialog(rootPane, "Η ταινία δεν ανήκει σε καμία Αγαπημένη Λίστα."
                    ,"Μήνυμα",JOptionPane.INFORMATION_MESSAGE);
        }           
       
    }//GEN-LAST:event_removeFromListButtonActionPerformed

    /*
        Ελεχος από το πεδίο κυκλοφορίας ταινίας για ύπαρξη τιμής  
        στα πεδία του είδους ταινίας και έτος κυκλοφορίας για  
        ενεργοποίηση/απενεργοποίηση του κουμπιού "Αναζήτηση"
    */
    private void yearMovieFieldEditorKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_yearMovieFieldEditorKeyPressed
        // TODO add your handling code here:
        /*
            Αν το πεδίο του τύπου ταινίας και το πεδίο του έτους κυκλοφορίας
            δεν είναι άδεια και τα δύο, το κουμπί "Αναζήτηση" ενεργοποιείται
            διαφορετικά απενεργοποιειται
        */
         if(!movieTypeComboBox.getSelectedItem().equals("<Κανένα>" ) 
                && !(yearMovieFieldEditor.getText().equals(null)))
            movieSearchButton.setEnabled(true);
        else
           movieSearchButton.setEnabled(false); 
    }//GEN-LAST:event_yearMovieFieldEditorKeyPressed

   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel addToListLabel;
    private javax.persistence.EntityManager em;
    private javax.swing.JComboBox<String> favoriteListComboBox;
    private java.util.List<model.FavoriteList> favoriteListList;
    private javax.persistence.Query favoriteListQuery;
    private javax.swing.JLabel headerJLaber;
    private javax.swing.JPanel headerJPanel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable movieResultTable;
    private javax.swing.JButton movieSearchButton;
    private javax.swing.JComboBox<String> movieTypeComboBox;
    private javax.swing.JLabel movieTypeLabel;
    private javax.swing.JButton removeFromListButton;
    private javax.swing.JButton resetChoicesButton;
    private javax.swing.JTextField yearMovieFieldEditor;
    private javax.swing.JLabel yearMovieLabel;
    private org.jdesktop.beansbinding.BindingGroup bindingGroup;
    // End of variables declaration//GEN-END:variables
    private List <Movie> retrieveMovieList;
    private MainMenu parent;    
    /*
        Μέθοδος ενημέρωσης πίνακα ταινιών αναζήτησης από 
        την λίστα αποτελεσμάτων αναζήτησης
    */
    private void addRowtoJTable (List<Movie> list){
        
        //Ανάκτηση μοντέλου πίνακα αποτελεσμάτων αναζήτησης 
        DefaultTableModel model =  (DefaultTableModel) movieResultTable.getModel();
        /*
            Δημιουργία του πίνακα με τα πεδία 'Τίτλος', 'Βαθμολογία' 
            και 'Περιγραφή' από την λίστα αποτελεσμάτων αναζήτησης
        */
        Object rowData[]; 
        rowData = new Object[3];
        model.setRowCount(0);
        for(int i=0; i<list.size(); i++){
            rowData[0] = list.get(i).getTitle();
            rowData[1] = list.get(i).getRating();
            rowData[2] = list.get(i).getOverview();
            model.addRow(rowData);
        }
    }    
    
    /*
        Μέθοδος Ανάκτησης από την Βάσει Δεδομένων των ταινιών που τηρούν
        τα κρητίρια αναζήτησης
    */
    private List <Movie> retrieveFromDBMovieTable (String genreID, String year){
        //Ανάκτηση των κλειδιών του είδους της ταινίας
        int genre_id = 0;
        switch(genreID){
            case "Action" :  genre_id = 28;
                break;
            case "Romance" : genre_id = 10749;
                break;
            case "Science Fiction" : genre_id = 878;
                break;        
        } 
        // Λίστα αποθήκευσης αποτελεσμάτων αναζήτησης
        List <Movie> movieSearchList = new ArrayList<>();
        // Ερώτημα στην Βάση Δεδομένων και τοποθέτηση της απάντησης στην λίστα
        try {    
            movieSearchList = em.createNamedQuery(
                "Movie.findByGenreAndYear",Movie.class).setParameter("genre_id",genre_id)
                .setParameter("year",year).getResultList();  
        }catch(Exception e){
            JOptionPane.showMessageDialog(rootPane, "Παρακαλώ επιλέξτε Τύπο ταινίας"
                    + "\nκαι έτος κυκλοφορίας της","Μήνυμα",JOptionPane.ERROR_MESSAGE);
        } 
        
        return movieSearchList;        
    } 
    
    //Μέθοδος Ανάκτησης των Αγαπημένων Λιστών από την Βάση Δεδομένων 
    private FavoriteList retrieveFavoriteListFromDB(int index){
         
        List <FavoriteList> favoriteList = new ArrayList<>();       
        favoriteList = em.createNamedQuery(
           "FavoriteList.findAll",FavoriteList.class).getResultList();        
        
        FavoriteList movieFavoriteList = favoriteList.get(index);
        return movieFavoriteList;
    }
    
    //Μέθοδος ανανέωσης ταινιων στη Βάση Δεδομένων
    private void updateMovieTabLe (Movie movie){
        
        em.getTransaction().begin();
               
        em.getTransaction().commit();          
        
    }
    
       
}
